[package]
name = "krampui"
version = "0.0.9"
authors = ["Snipcola"]
license = "MIT"
edition = "2021"

[build-dependencies]
tauri-build = { version = "1", features = [] }

[dependencies]
tauri = { version = "1", features = [ "system-tray", "api-all"] }
tauri-plugin-single-instance = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v1" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sysinfo = "0.30.7"
rdev = "0.5.3"

[features]
custom-protocol = ["tauri/custom-protocol"]
